### ISSUE TITLE
URL/Path construction function?

### ISSUE THREAD

**Issue by saurabhnanda** [chpatrick/servant-generic#1]
After one has used `servant-generic` to define named routes, is there any way to use the same named routes to generate a URL/path? 

For example, referring to the project README...

```
data Site route = Site
  { about :: route :-
      "about" :> Get '[PlainText] Text
  , faq :: route :-
      "faq" :> Get '[PlainText] Text
  } deriving Generic
```

...ss there any way to do the following:

```
urlFunctions = Site AsFunctions
---
<a href="{about urlFunctions}">About us</a>
```

**Comment by roberth** [comment]
This can be done after #3 but after that, needs to be documented with an example.

**Comment by chpatrick** [comment]
This is now merged. You can use `fieldLink about` to do what you described. :)

**Comment by saurabhnanda** [comment]
Brilliant :) Has this been released on Hackage?

**Comment by chpatrick** [comment]
Yep: http://hackage.haskell.org/package/servant-generic-0.1.0.1/docs/Servant-Generic.html#v:fieldLink
