### ISSUE TITLE
Do you mind if `servant-generic` is merged into `servant`

### ISSUE THREAD

**Issue by phadej** [chpatrick/servant-generic#16]
I ended up re-implementing the very same functionality, but I like yours implementation with type families more. And I was aware of `servant-generic` but somehow forgot it exists. Having it in `servant`, `servant-server` etc. would help people discover this handy approach!

**Comment by chpatrick** [comment]
By all means go ahead, some credit would be nice though. :)

**Comment by phadej** [comment]
Surely!

**Comment by domenkozar** [comment]
https://github.com/haskell-servant/servant/pull/1003

**Comment by alpmestan** [comment]
Merged! Thanks.
