### ISSUE TITLE
Record De-Structuring and Sub-APIs

### ISSUE THREAD

**Issue by sordina** [chpatrick/servant-generic#4]
Hi!

Not really an issue, but more of a question that might possibly be turned into a feature request, not sure!

I'd like to be able to destruct APIs into clients without using the normal servant operators (:<|>).

Similarly, I'd like to be able to nest APIs, without having to use ToServant to convert them back into old-school servant API types... Is this at all possible, or am I on the wrong track?

No pressure, just wanted to get some feedback on if this is doable or not!

![image](https://user-images.githubusercontent.com/92299/32711669-3864f932-c894-11e7-99db-f9a5b0fdda2f.png)

**Comment by chpatrick** [comment]
Hi, sorry for getting back to you so late,

Unfortunately, this would make the records incompatible with the Servant ecosystem, which expects a `:<|>` tree. However, my [solga](https://github.com/chpatrick/solga) library works exactly as you described. :)

**Comment by domenkozar** [comment]
@sordina you can get pretty close with https://github.com/chpatrick/servant-generic/issues/10
