### ISSUE TITLE
For god's sake please provide a simple error message if the route record is missing an instance of `Generic`

### ISSUE THREAD

**Issue by sras** [chpatrick/servant-generic#7]
I have lost more than a day on two separate occasions chasing down this simple thing. Please find a way to provide a simple error message that says "Hey, please derive/implement a Generic instance for your routes record", Instead of a dozen pages of incomprehensible type jargon!

**Comment by chpatrick** [comment]
Could you paste an example of such an error message?

**Comment by qrilka** [comment]
In my case the error came from generating Swagger doc, the error was like:
```
    /home/qrilka/ws/project/src/Project/Swagger.hs:311:14: error:
        • No instance for (HasSwagger
                             (Servant.Generic.GToServant
                                (GHC.Generics.Rep (SomeAPI Servant.Generic.AsApi))))
            arising from a use of ‘toSwagger’
        • In the expression: toSwagger publicApi
          In an equation for ‘swaggerDoc’: swaggerDoc = toSwagger publicApi
```
